"""agent runs and audit log

Revision ID: 734ed89dc826
Revises: 3d266701391b
Create Date: 2026-10-09 10:06:08.056010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '734ed89dc826'
down_revision: Union[str, Sequence[str], None] = '3d266701391b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='running', nullable=False),
    sa.Column('utterance', sa.Text(), nullable=False),
    sa.Column('suspension', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('running','awaiting_input','awaiting_approval','completed','rejected','failed')", name='ck_agent_runs_status'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_seller_created', 'agent_runs', ['seller_id', 'created_at'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='success', nullable=False),
    sa.Column('undoable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('inverse', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('success','failed','refused')", name='ck_agent_actions_status'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_actions_seller_created', 'agent_actions', ['seller_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_actions_seller_created', table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index('ix_agent_runs_seller_created', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
