"""orders and order items

Revision ID: be62e5698aa4
Revises: 734ed89dc826
Create Date: 2026-10-09 10:53:21.094426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be62e5698aa4'
down_revision: Union[str, Sequence[str], None] = '734ed89dc826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=24), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='paid', nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending','paid','shipped','delivered','cancelled')", name='ck_orders_status'),
    sa.CheckConstraint('total_paise >= 0', name='ck_orders_total_non_negative'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'order_number', name='uq_orders_seller_number')
    )
    op.create_index('ix_orders_seller_placed', 'orders', ['seller_id', 'placed_at'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category_slug', sa.String(length=64), nullable=True),
    sa.Column('unit_price_paise', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total_paise', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_order', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_seller_placed', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
